# Expt 4
## Aim: Implement Perceptron Learning Rule

In [2]:
import numpy as np
import pandas as pd

In [3]:
X= np.array([ [1, -2, 0, -1], [0, 1.5, -0.5, -1], [-1, 1, 0.5, -1] ])
W = np.array([1, -1, 0, 0.5])
W = W.T
Y = np.array([-1, -1, 1])
b = 0
epoch = 5
error = []

c = 0.1

In [4]:
print("Inputs: \n", X)
print("Weights: \n", W)
print("Targets: \n", Y)

Inputs: 
 [[ 1.  -2.   0.  -1. ]
 [ 0.   1.5 -0.5 -1. ]
 [-1.   1.   0.5 -1. ]]
Weights: 
 [ 1.  -1.   0.   0.5]
Targets: 
 [-1 -1  1]


In [5]:
def signum(x):
    if x<0:
        return -1
    else:
        return 1

In [5]:

for t in range(epoch):
    total_error = 0
    for (i, x) in enumerate(X):
        y = Y[i]

        net = np.dot(x, W)
        # print("Net: ", net)

        fnet = signum(net)
        # print("F(net): ", fnet)
        

        delW =c*(np.dot(y - fnet, x))

        W += delW

    print(f"\nEnd Of Epoch -> {t}")
    print(f"Net:-> {net:.3f}  F(net):-> {fnet}")
    print(W)


# error_df = pd.DataFrame(error)

# print("Errors: \n", error_df)



End Of Epoch -> 0
Net:-> -2.100  F(net):-> -1
[ 0.6 -0.4  0.1  0.5]

End Of Epoch -> 1
Net:-> -1.050  F(net):-> -1
[0.2 0.2 0.2 0.5]

End Of Epoch -> 2
Net:-> -0.400  F(net):-> -1
[5.55111512e-17 4.00000000e-01 3.00000000e-01 3.00000000e-01]

End Of Epoch -> 3
Net:-> -0.200  F(net):-> -1
[-0.2  0.3  0.5  0.3]

End Of Epoch -> 4
Net:-> 0.450  F(net):-> 1
[-0.2  0.3  0.5  0.3]


# Using Random Function

In [17]:
X= np.array([ [1, -2, 0, -1], [0, 1.5, -0.5, -1], [-1, 1, 0.5, -1] ], dtype='int64')
W = np.random.randint(-2, 2, (4), dtype='int64')
W = np.array(W, dtype='float')
W = W.T
Y = np.array([-1, -1, 1])
b = 0
epoch = 10
c = 0.1

In [18]:
print("Inputs: \n", X)
print("Weights: \n", W)
print("Targets: \n", Y)

Inputs: 
 [[ 1 -2  0 -1]
 [ 0  1  0 -1]
 [-1  1  0 -1]]
Weights: 
 [ 0. -1. -1. -2.]
Targets: 
 [-1 -1  1]


In [19]:

for t in range(epoch):

    for (i, x) in enumerate(X):
        y = Y[i]
        net = np.dot(x, W)
        fnet = signum(net)
        delW = c*(np.dot(y - fnet, x)) 

        W += delW

    print(f"\nEnd Of Epoch -> {t}")
    print(f"Net:-> {net:.2f} F(net):-> {fnet}")
    print(W)



End Of Epoch -> 0
Net:-> 1.00 F(net):-> 1
[-0.2 -0.8 -1.  -1.6]

End Of Epoch -> 1
Net:-> 1.00 F(net):-> 1
[-0.4 -0.6 -1.  -1.2]

End Of Epoch -> 2
Net:-> 1.00 F(net):-> 1
[-0.6 -0.4 -1.  -0.8]

End Of Epoch -> 3
Net:-> 1.00 F(net):-> 1
[-0.8 -0.2 -1.  -0.4]

End Of Epoch -> 4
Net:-> 1.00 F(net):-> 1
[-1.00000000e+00 -5.55111512e-17 -1.00000000e+00 -2.77555756e-16]

End Of Epoch -> 5
Net:-> 0.60 F(net):-> 1
[-1.  -0.2 -1.   0.2]

End Of Epoch -> 6
Net:-> 0.60 F(net):-> 1
[-1.  -0.2 -1.   0.2]

End Of Epoch -> 7
Net:-> 0.60 F(net):-> 1
[-1.  -0.2 -1.   0.2]

End Of Epoch -> 8
Net:-> 0.60 F(net):-> 1
[-1.  -0.2 -1.   0.2]

End Of Epoch -> 9
Net:-> 0.60 F(net):-> 1
[-1.  -0.2 -1.   0.2]


# Testing Model On User Input

In [41]:

# X = [[int(input("Enter Inputs: ")) for j in range(4) ] for i in range(3) ]

X = [float(input("Enter Inputs: ")) for i in range(4)]
X = np.array(X)

Target = np.array([-1, -1, 1])
# W = np.array([-0.2,  0.3,  0.5,  0.3])
W = np.array([-1, -0.2, -1, 0.2])
W = W.T


In [42]:
print("Input Entered by user: ", X)

print("\nWeights: ", W)

Input Entered by user:  [ 1. -2.  0. -1.]

Weights:  [-1.  -0.2 -1.   0.2]


In [44]:
Y = signum(np.dot(X, W))
print("Calculated Output: ", Y)
print("\nExpected Outputs: ", Target)

Calculated Output:  -1

Expected Outputs:  [-1 -1  1]


## Conclusion:
## Perceptron learning rule was successfully studied and implemented.