# Expt 3

## Aim: Implement Hebbian Learning Rule

In [2]:
#import dependencies
import numpy as np

In [23]:
X = np.array([[1, -2, 1.5, 0], [1, -0.5, -2, -1.5], [0, 1, -1, 1.5]])
W = np.array([1, -1, 0, 0.5])
W = W.T
c = 0.1
epoch = 10

In [24]:
print("Inputs: \n", X)
print("\nWeights : \n", W)

Inputs: 
 [[ 1.  -2.   1.5  0. ]
 [ 1.  -0.5 -2.  -1.5]
 [ 0.   1.  -1.   1.5]]

Weights : 
 [ 1.  -1.   0.   0.5]


In [6]:
# signum function
def signum(x):
    return -1 if x<0 else 1

In [26]:
for t in range(epoch):
        for (i, x) in enumerate(X):
            net = np.dot(x, W)
            fnet = signum(net)

            delW = np.dot(x, c*fnet)
            W += delW
            
        print(f"\nIteration:-> {t}")
        print("W ==>", W)
        # print("▽W ==>", delW)



Iteration:-> 0
W ==> [ 1.2  -1.35  0.05  0.2 ]

Iteration:-> 1
W ==> [ 1.4 -1.7  0.1 -0.1]

Iteration:-> 2
W ==> [ 1.6  -2.05  0.15 -0.4 ]

Iteration:-> 3
W ==> [ 1.8 -2.4  0.2 -0.7]

Iteration:-> 4
W ==> [ 2.   -2.75  0.25 -1.  ]

Iteration:-> 5
W ==> [ 2.2 -3.1  0.3 -1.3]

Iteration:-> 6
W ==> [ 2.4  -3.45  0.35 -1.6 ]

Iteration:-> 7
W ==> [ 2.6 -3.8  0.4 -1.9]

Iteration:-> 8
W ==> [ 2.8  -4.15  0.45 -2.2 ]

Iteration:-> 9
W ==> [ 3.  -4.5  0.5 -2.5]


# Using random Weignt initialization 

In [8]:
X = np.array([[1, -2, 1.5, 0], [1, -0.5, -2, -1.5], [0, 1, -1, 1.5]], dtype = 'int64')
W = np.random.randint(-1, 1, (4), dtype='int64')
W = np.array(W)
W = W.T
c = 1
epoch = 10

In [9]:
print(W)

[ 0 -1  0 -1]


In [10]:
for t in range(epoch):
        for (i, x) in enumerate(X):
            net = np.dot(x, W)
            fnet = signum(net)

            delW = c*(np.dot(x, fnet))
            W += delW
            
        print("\nIteration:-> ", t)
        print("W ==>", W)


Iteration:->  0
W ==> [ 2 -4  0 -3]

Iteration:->  1
W ==> [ 4 -7  0 -5]

Iteration:->  2
W ==> [  6 -10   0  -7]

Iteration:->  3
W ==> [  8 -13   0  -9]

Iteration:->  4
W ==> [ 10 -16   0 -11]

Iteration:->  5
W ==> [ 12 -19   0 -13]

Iteration:->  6
W ==> [ 14 -22   0 -15]

Iteration:->  7
W ==> [ 16 -25   0 -17]

Iteration:->  8
W ==> [ 18 -28   0 -19]

Iteration:->  9
W ==> [ 20 -31   0 -21]


## Trained weights after 10 iterations:
### [ 20 -31   0 -21]

## Conclusion:
## Hebbian learning rule was successfully studied and implemented