# Expt 6
## Aim: Implement Supervised Learning using Delta learning rule

In [1]:
import numpy as np

In [56]:
X = np.array([[0, 1, 1, 1], 
              [1, 0, 1, 0],
              [0, 1, 1, 0], 
              [1, 1, 1, 1]])

W = np.random.randint(-2, 4, (4), dtype='int64')
W = np.array(W, dtype='float')
W = W.T

Y = np.array([0, 1, 0, 1])
c = 0.1
epoch = 8000


In [57]:
def UpSigmoid(x):
  return (1 / (1 + np.exp(-x) ) )

In [58]:
def fdNet(x):
  return x*(1 - x)

In [59]:
for t in range(epoch):
  for (i, x) in enumerate(X):
    y = Y[i]
    net = np.dot(x, W)
    fnet = UpSigmoid(net)
    fdnet = fdNet(fnet)

    delW = c*(np.dot((y- fnet)*fdnet, x ))
    W += delW

  print(f"\n End of Epoch -> {t}")
  print(W)

Streaming output truncated to the last 5000 lines.
 End of Epoch -> 6333
[ 6.14095674 -4.32712534 -0.08266256  1.36903532]

 End of Epoch -> 6334
[ 6.14113523 -4.32716024 -0.08269692  1.36901467]

 End of Epoch -> 6335
[ 6.1413137  -4.32719514 -0.08273127  1.36899401]

 End of Epoch -> 6336
[ 6.14149214 -4.32723003 -0.08276562  1.36897336]

 End of Epoch -> 6337
[ 6.14167054 -4.32726491 -0.08279996  1.36895271]

 End of Epoch -> 6338
[ 6.14184892 -4.32729979 -0.0828343   1.36893207]

 End of Epoch -> 6339
[ 6.14202727 -4.32733467 -0.08286863  1.36891143]

 End of Epoch -> 6340
[ 6.14220559 -4.32736953 -0.08290295  1.3688908 ]

 End of Epoch -> 6341
[ 6.14238387 -4.3274044  -0.08293727  1.36887017]

 End of Epoch -> 6342
[ 6.14256213 -4.32743925 -0.08297159  1.36884954]

 End of Epoch -> 6343
[ 6.14274036 -4.3274741  -0.0830059   1.36882891]

 End of Epoch -> 6344
[ 6.14291856 -4.32750895 -0.0830402   1.36880829]

 End of Epoch -> 6345
[ 6.14309673 -4.32754379 -0.0830745   1.36878768]



## Hence the trained weights are
## [ 4.47458252, -1.23116005, -1.16443416,  0.08745907]


In [60]:
# test inputs
x1 = np.array([0, 1, 1, 1]) 
x2 = np.array([1, 0, 1, 0])
x3 = np.array([0, 1, 1, 0]) 
x4 = np.array([1, 1, 1, 1])

trainedW = np.array([ 6.40339224, -4.37856825, -0.13337354,  1.33900972])


In [63]:
# test 1
net1 = np.dot(x1, trainedW)
y1 = UpSigmoid(net1)
print(y1)
print("Expected Output: ", Y[0])

0.040197139629297746
Expected Output:  0


In [64]:
# test 2
net2 = np.dot(x2, trainedW)
y2 = UpSigmoid(net2)
print(y2)
print("Expected Output: ", Y[1])

0.9981113804342313
Expected Output:  1


In [66]:
# test 3
net3 = np.dot(x3, trainedW)
y3 = UpSigmoid(net3)
print(y3)
print("Expected Output: ", Y[2])

0.010857935293277813
Expected Output:  0


In [67]:
# test 4
net4 = np.dot(x4, trainedW)
y4 = UpSigmoid(net4)
print(y4)
print("Expected Output: ", Y[3])

0.9619645935373927
Expected Output:  1


In [68]:
# Done

## Conclusion:
## Supervised learning rule using delta learning rule was successfully studied and implemented.