# Expt 7

## Aim: Implement Widrow Hoff Learning Rule 

In [2]:
import numpy as np

In [11]:
X = np.array([[0, 1, 1, 1],
              [1, 0, 1, 0],
              [0, 1, 1, 0], 
              [1, 1, 1, 1]
              ])

W = np.random.randint(-1, 2, (4), dtype='int64')
W = np.array(W, dtype='float')
W = W.T

Y = np.array([0, 1, 0, 1])

C = 0.5;
epoch = 30

In [12]:
for t in range(epoch):
  for (i, x) in enumerate(X):
    y = Y[i]
    net = np.dot(x, W)
    delW = C*(np.dot((y - net), x))
    W += delW

  print(f"\nEnd of Epoch -> {t}")
  print(W)


End of Epoch -> 0
[ 1.25  0.5  -1.   -0.25]

End of Epoch -> 1
[ 1.15625  0.375   -0.9375  -0.15625]

End of Epoch -> 2
[ 1.08203125  0.265625   -0.8359375  -0.08203125]

End of Epoch -> 3
[ 1.02587891  0.17382812 -0.71386719 -0.02587891]

End of Epoch -> 4
[ 0.98565674  0.09985352 -0.58532715  0.01434326]

End of Epoch -> 5
[ 0.95890045  0.04275513 -0.46037292  0.04109955]

End of Epoch -> 6
[ 9.43074226e-01  8.27789307e-04 -3.45693588e-01  5.69257736e-02]

End of Epoch -> 7
[ 0.93575156 -0.02804899 -0.2452457   0.06424844]

End of Epoch -> 8
[ 0.93473275 -0.04614872 -0.16085991  0.06526725]

End of Epoch -> 9
[ 0.93811152 -0.05570798 -0.09279094  0.06188848]

End of Epoch -> 10
[ 0.94430246 -0.05879823 -0.04019409  0.05569754]

End of Epoch -> 11
[ 0.95203982 -0.05724789 -0.00152163  0.04796018]

End of Epoch -> 12
[ 0.96035677 -0.05260403  0.0251608   0.03964323]

End of Epoch -> 13
[ 0.96855238 -0.04612363  0.04193241  0.03144762]

End of Epoch -> 14
[ 0.97615233 -0.03878563  0.05

## The trained weights are:
## [ 1.0015292,   0.00232422, -0.00244589, -0.0015292 ]

In [3]:
# Test inputs
x1 = np.array([1, 0, 0, 0])
x2 = np.array([0, 0, 0, 0])

trainedW = [ 1.0015292, 0.00232422, -0.00244589, -0.0015292 ]

In [4]:
# test 1
Y1 = np.dot(x1, trainedW)

print(Y1)
print("Expected Output: 1")

1.0015292
Expected Output: 1


In [5]:
# test 2
Y2 = np.dot(x2, trainedW)

print(Y2)
print("Expected Output: 0")

0.0
Expected Output: 0


## Conclusion:
## Widrow Hoff Learning rule was successfully studied and implemented.