# Expt 5

## Aim: Implement Delta Learning Rule


In [1]:
import numpy as np

In [10]:
X = np.array([[0, 1, 1, 1],
              [1, 0, 1, 0],
              [0, 1, 1, 0], 
              [1, 1, 1, 1]
              ])
W = np.random.randint(-1, 2, (4), dtype='int64')
W = np.array(W, dtype='float')
W = W.T

Y = np.array([0, 1, 0, 1])

C = 1;
epoch = 500

In [11]:
# Unipolar sigmoid
def upSigmoid(x):
    return (1 - np.exp(-x))/(1 + np.exp(-x))


In [12]:
# to claculate f'(net)
def fdNet(fnet):
  return (1 - fnet**2) / 2;

In [13]:
for t in range(epoch):
  for (i, x) in enumerate(X):
    y = Y[i]

    net = np.dot(x, W)
    fnet = upSigmoid(net)
    fdnet = fdNet(fnet)

    delW = C*(np.dot((y - fnet)*fdnet, x))
    W += delW
  
  print(f"\nEnd Of Epoch -> {t}")
  print(W)




End Of Epoch -> 0
[ 0.57237875  0.96286118  1.22296416 -0.86943972]

End Of Epoch -> 1
[ 0.83875123  0.77541701  1.12902526 -0.88902256]

End Of Epoch -> 2
[ 1.10209568  0.6000912   1.02441679 -0.87917108]

End Of Epoch -> 3
[ 1.34145192  0.43918273  0.91600807 -0.8478558 ]

End Of Epoch -> 4
[ 1.54610226  0.29771492  0.81413797 -0.79932465]

End Of Epoch -> 5
[ 1.71520932  0.17907097  0.72649359 -0.73685732]

End Of Epoch -> 6
[ 1.85369953  0.08240051  0.65519585 -0.66551891]

End Of Epoch -> 7
[ 1.967823    0.00442497  0.59883749 -0.5910008 ]

End Of Epoch -> 8
[ 2.06305299 -0.05842218  0.55498665 -0.51783238]

End Of Epoch -> 9
[ 2.14368803 -0.10926621  0.52121046 -0.44894901]

End Of Epoch -> 10
[ 2.21299478 -0.15069948  0.49535245 -0.38597056]

End Of Epoch -> 11
[ 2.27343065 -0.18480191  0.47561904 -0.32958018]

End Of Epoch -> 12
[ 2.32684037 -0.21319231  0.46058835 -0.27984427]

End Of Epoch -> 13
[ 2.37461226 -0.23710407  0.44916882 -0.2364554 ]

End Of Epoch -> 14
[ 2.417797

### Hence the trained weigths are 
### [4.25652194e+00, -6.05602217e-01,  6.07374772e-01,  1.31195807e-03]


## Testing Given test case

### input x = [1, 0, 0, 0]   output = 1
### input x = [0, 0, 0, 0]   output = 0

In [14]:
# Test inputs
x1 = np.array([1, 0, 0, 0])
x2 = np.array([0, 0, 0, 0])
TrainedWeight = np.array([4.25652194e+00, -6.05602217e-01,  6.07374772e-01,  1.31195807e-03])


In [17]:
# test 1
net1 = np.dot(x1, TrainedWeight)
Y1 = (upSigmoid(net1))
print(Y1)
print("Expected Ouput: 1")

0.9720530382551299
Expected Ouput: 1


In [18]:
# test 2
net2 = np.dot(x2, TrainedWeight)
Y2 = (upSigmoid(net2))
print(Y2)
print("Expected Output: 0")

0.0
Expected Output: 0


## Conclusion:
## Delta learning rule was successfully studied and implemented.